### ISSUE TITLE
Parse des fichiers Omégawatt

### ISSUE THREAD

**Issue by tglatt** [Augustin82/omegawatt#1]
Pour le parse des fichiers Omégawatt, je souhaite ajouter en 2ème ligne colonne 1 un code permettant de connaitre le format du fichier et de parser en conséquence.
Code:  MV_Txx_Vyyy
xx:  numéro du type de fichier   (correspond à une sélection à faire dans une liste pour l'envoi automatique des fichiers sur le serveur FTP par nos appareils)
yyy: numéro de version du fichier pour ce type.

**Comment by pf26** [comment]
Rectif:
Code: MV_Txxx_Vyyy
xxx: numéro du type de fichier   Les fichiers à traiter sont en type 300 (nous adapterons le parser ultérieurement pour d'autres types).
Le numéro de type apparait également dans le nom des fichiers de données qui est de forme:
T300_210708_120008.tsv         Txxx_yymmdd_hhmmss.tsv

Exemple de début de fichier:
02000004	Volts	Volts	Volts	02000004	02000004	02000004	02000004	02000004	02000004	02000004	02000004	02000004	02000004	02000004	02000004
MV_T300_V001	Ph 1	Ph 2	Ph 3	Voie1     	Voie1      R	Voie2     	Voie2      R	Voie3     	Voie3      R	Voie4     	Voie4      R	Voie5     	Voie5      R	Voie6     	Voie6      R
19/05/21 00:10:00	247.71	244.05	240.51	12	-26	0	0	42	-11	0	0	0	0	0	0
19/05/21 00:20:00	247.70	244.39	240.25	12	-26	0	0	2	-17	0	0	0	0	0	0

Compter le nbre de colonnes en première ligne. Il y en a 16 + 12*n  ou n=nbre esclave
Si nb colonnes -16 pas divisible par 12 -> erreur format entête
En seconde ligne col 1, lire  MV_T300_V001 et vérifier le T300  (split après le premier "_")
à partir de ligne 3, si la col1 n'est pas une date/heure valide -> arrêter le traitement

**Comment by pf26** [comment]
Concernant les types de fichier à parser, en fait, ce n'est pas T300 qu'il faut vérifier, mais T?00  (le premier digit pourra être différent, car il dépend du pas de temps des données dont on dispose.  Le "3" correspond au pas de temps 10min, mais j'aimerais bien que tout soit compatible avec un autre pas de temps (du coté grafana, ça devrait marcher).

**Comment by Augustin82** [comment]
Parsing OK, sans le traitement d'erreur pour l'instant (je rappelle le besoin ci-dessous, pour info) :

- Si nb colonnes -16 pas divisible par 12 -> erreur format entête
- En seconde ligne col 1, lire MV_T300_V001 et vérifier le T300 (split après le premier "_")
  en fait, ce n'est pas T300 qu'il faut vérifier, mais T?00
- à partir de ligne 3, si la col1 n'est pas une date/heure valide -> arrêter le traitement
