### ISSUE TITLE
Peuplement de la table device à partir d'un Excel

### ISSUE THREAD

**Issue by Augustin82** [Augustin82/omegawatt#12]
Entamer une réflexion sur le sujet.

**Comment by pf26** [comment]
L'idéal pour moi serait qu'un utilisateur puisse accéder à un tableau à 5 colonnes :
- device name  (= le nom qui serait mis dans le champs device name de la base)
- SN  (= SN du Maitre ou Esclave, exemple 02000015)
- Channel  (=voie1 à 6, actuellement mis dans colonne "nature")
- date début
- date fin
- optionnellement suivis de la colonne "usage", 
Il pourrait y avoir un même device name pour plusieurs couples SN/Channel, donc plusieurs lignes avec le même device name, auquel cas, l'affichage dans Grafana fera la somme des voies mesurées (c'est le cas pour un appareil triphasé où on mesure chaque phase avec une voie différente)
Il faudrait idéalement une fonction pour mettre à jour la base (c'est à dire écraser le device name pour tous les enregistrements entre date début et date fin ayant le couple SN/Channel des lignes du tableau)

Plutôt qu'un tableau, on pourrait envoyer par FTP un fichier device_table.txt, à parser, traiter, puis mettre à jour la base quand il est reçu.

Il faut préalablement corriger le fait que les SN sont dans la colonne "device_name". Il serait judicieux aussi de corriger le fait que les nom des voies sont dans "nature". Je préfèrerais avoir une colonne "SN" et une colonne "Channel" dans la base. 
Il faudrait à la fois changer le parser, et mettre à jour la base pour les data déjà parsées (ou effacer/reparser les fichiers)

**Comment by pf26** [comment]
Pour le tableau device_name ou le fichier device_table.txt, je souhaite ajouter une colonne coefficient, permettant de multiplier la valeur du fichier par ce coefficient, avant mise en base de donnée.
La table devrait permettre qu'il y ait plusieurs lignes pour le même couple SN/Channel, avec des coef différents selon les dates. S'il y a recouvrement des dates début et fin pour un même couple SN/Channel, c'est la dernière ligne du fichier qui est prioritaire.

**Comment by Augustin82** [comment]
Comment gère-t-on le fait que certaines colonnes ne sont pas composées de "serial number + channel", comme par exemple les colonnes Ph1, Ph2, Ph3 ?

**Comment by pf26** [comment]
Pour le sn, dans le fichier de mesure, on peut prendre celui de la colonne précédente (donc la première colonne, en haut)
Pour le channel, on peut utiliser Ph1, Ph2 et Ph3.  (idéalement non dépendant de la casse)

Donc la table device pourrait ressembler à:
sn    channel    device name    start date    coef    usage
02000015    ph1    Séchoir    20/08/2021 10:00:00    1    séchage
02000015    ph2    Séchoir    20/08/2021 10:00:00    1    séchage
02000015    ph3    Séchoir    20/08/2021 10:00:00    1    séchage
02000015    1   Borne Charge    20/08/2021 10:00:00    1    mobilité
02000015    2   Borne Charge    20/08/2021 10:00:00    1    mobilité
02000015    3    Borne Charge    20/08/2021 10:00:00    1 mobilité
04000026    1    Gén séchoir    20/08/2021 10:00:00    1    séchage
04000026    2    Gén séchoir    20/08/2021 10:00:00    1    séchage
04000026    3    Gén séchoir    20/08/2021 10:00:00    1    séchage
04000026    4    Process séchoir    20/08/2021 10:00:00    1 séchage
...

Il y aura fréquement des lignes avec le même device_name. ça doit me permettre de faire les sommes facilement  (il s'agit de mesures sur les 3 phases, il faut sommer pour avoir la puissance totale de l'appareil)

**Comment by Augustin82** [comment]
Super, merci !
