### ISSUE TITLE
Évolution parsing Socomec

### ISSUE THREAD

**Issue by Augustin82** [Augustin82/omegawatt#15]
Pierre a dit :
> Je remarque qu'il y a aussi des données à 10 minutes (de puissance
active P+), qui sont dans les fichiers  * _LoadCurve_*  tels que `WESTRUP_LoadCurve_2021-07-14_00-00-13.csv`

>Le format est du genre:
```
ï»¿"Device name","IP Address","Modbus Address","Begin date","End date"
WESTRUP,0.0.0.0,5,2021-07-12T23:54:59,2021-07-13T23:55:00,

Load Name,WESTRUP,
Usage,"Heating",
Nature,"Elec",
Measured value,"P+",
Unit,"W",
Scale,1.0000000,
Date,"Values","Flags"
2021-07-13T23:50:00,200,"Full integration period and date/time set"
2021-07-13T23:40:00,200,"Full integration period and date/time set"
2021-07-13T23:30:00,200,"Full integration period and date/time set"
```

> ce qui serait intéressant, c'est de parser aussi ces fichiers et
mettre dans "P+" les valeurs (ici 200 W)
Je vois dans le bucket qu'il y a déjà des données de ce type (entre
2020/03 et 2020/06 pour Gene TRANSFO par exemple) donc le parser a du
être fait ? (je n'ai pas vérifié les sources pour voir)
Ca m'arrangerait que ça puisse se faire, car les données sont plus
fines, et ça permet aussi de voir le temps que prennent des requêtes
avec cette granularité (mais sans dérivative).
Après, ce n'est pas explicitement demandé par l'Herbier, si ça pose
soucis, on laisse tomber.

**Comment by pf26** [comment]
On peut clore, c'est déjà fait.
