### ISSUE TITLE
Gestion du fuseau horaire des horodatages

### ISSUE THREAD

**Issue by Augustin82** [Augustin82/omegawatt#16]
Pour l'instant les horodatages omegawatt sont interprétés comme étant en UTC/GMT, ce qui n'est peut-être pas le cas.

**Comment by pf26** [comment]
En effet, ce n'est pas le cas. Les dates/heures des fichiers sont en heure locale (CET-1CEST,M3.5.0,M10.5.0/3)

**Comment by pf26** [comment]
J'aimerais que cette issue soit traitée avant que l'on mette à jour la base de données. Actuellement, les mesures Omegawatt sont encore décalées de +2heures  (3h50 en base pour 1h50 en réel)

**Comment by Augustin82** [comment]
> En effet, ce n'est pas le cas. Les dates/heures des fichiers sont en heure locale (CET-1CEST,M3.5.0,M10.5.0/3)

Je ne suis pas familier avec cette notation, mais c'est l'heure de Paris, c'est ça ? Europe/Paris ? Si oui, je peux faire en sorte que l'on "interprète" le timestamp comme étant dans cette timezone (vu que cette information n'est pas portée par le timestamp), afin de le rendre "absolu".

**Comment by pf26** [comment]
Oui, c'est l'heure de Paris. Effectivement, tu peux interprêter le timestamp comme étant de cette timezone.

**Comment by Augustin82** [comment]
Résolu par eb6fe0b99a960f3d48b451b9fd32918a08fc0fc9
