### ISSUE TITLE
Enregistrement des données dans influxdb

### ISSUE THREAD

**Issue by tglatt** [Augustin82/omegawatt#3]
la sauvegarde des données échoue sur le serveur d'omegawatt. Il faut sauvegarder les données en lot et non une à une

**Comment by pf26** [comment]
Sur le Kimsuffi K-3 ?
Tu parles de créer un backup des données reçues ? (ça semble nécessaire, notamment pour Socomec qui ne garde probablement pas les données en mémoire bien longtemps) - Sur les systèmes Omégawatt, les données 10 min restent stockées 80 ans, donc en théorie, on doit pouvoir les retrouver...

**Comment by tglatt** [comment]
Je me suis mal exprimé. Il y a un problème lors de l'enregistrement des mesures en base. Quand le volume est trop important, ca échoue. Du coup, je dois reprendre le mécanique d'enregistrement des données dans InfluxDB :-)

**Comment by tglatt** [comment]
le problème était du à une erreur dans les fichiers SOCOMEC. maintenant on teste si la valeur est bien un entier avant d'enregistrer une données
