### ISSUE TITLE
Gestion des repertoires des clients

### ISSUE THREAD

**Issue by tglatt** [Augustin82/omegawatt#4]
Il faut gérer un répertoire par client et savoir s'il faut utiliser le parsing socomec ou omegawatt

**Comment by pf26** [comment]
Je propose une architecture de répertoire telle que :
/clientx/yyyy/SNmaitre/ pour les données de chaque système omégawatt  (un boitier maitre par système)
/clientx/yyyy/socomec/  pour les données socomec
yyyy: numéro ou nom de projet du clientx
