### ISSUE TITLE
Sauvegarde des fichiers traités

### ISSUE THREAD

**Issue by tglatt** [Augustin82/omegawatt#5]
On souhaite conserver les fichiers traités. Une fois traité, renommer le fichier avec un "_" devant par exemple

**Comment by pf26** [comment]
Après réflection, si on a un paquet de fichiers à traiter de nouveau pour reconstituer une base, c'est peut être long de virer le "_" en début de nom de chaque fichier. C'est surement plus simple si on créé un répertoire /done et on met déplace les fichiers traités dedans.   (il suffira de les remettre où ils étaient) 
Ca évite d'avoir à tester les noms de fichiers dans le parser (pour ne pas traiter les fichiers commençant par "_"), en revanche, si le parser se balade dans tous les sous-répertoire, il devra ne pas traiter les fichiers dans les répertoires /done.. 
Désolé pour le contre-ordre,  si c'est déjà implémenté, tant pis, je prends comme c'est.
